services:
  web:
    build: .
    command: flask run --host=0.0.0.0 --port=5000
    volumes:
      - ./app:/usr/src/app/app
      - ./scripts:/usr/src/app/scripts
    environment:
      - DATABASE_URL=postgresql+psycopg2://postgres:postgres@db:5432/retrofagia
      - SECRET_KEY=super-secret-key
    depends_on:
      - db
    ports:
      - "80:5000"

  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_DB=retrofagia
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
